
image: amazoncorretto:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - /bin/bash -c "./gradlew assemble"  # Specify the shell interpreter
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - /bin/bash -c "./gradlew check clean"  # Specify the shell interpreter

