image: amazoncorretto:21

stages:
  - build
  - test

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew check clean
